version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: hotel-postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hotel-db
      POSTGRES_USER: hotel_user_admin
      POSTGRES_PASSWORD: 12345678
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
