version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: hotel-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hotel
      POSTGRES_USER: hotel_user
      POSTGRES_PASSWORD: hotel_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
